# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedDublinCoreElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('term', models.CharField(choices=[('AB', 'Abstract'), ('AR', 'AccessRights'), ('AM', 'AccrualMethod'), ('AP', 'AccrualPeriodicity'), ('APL', 'AccrualPolicy'), ('ALT', 'Alternative'), ('AUD', 'Audience'), ('AVL', 'Available'), ('BIB', 'BibliographicCitation'), ('COT', 'ConformsTo'), ('CN', 'Contributor'), ('CVR', 'Coverage'), ('CRD', 'Created'), ('CR', 'Creator'), ('DT', 'Date'), ('DTA', 'DateAccepted'), ('DTC', 'DateCopyrighted'), ('DTS', 'DateSubmitted'), ('DSC', 'Description'), ('EL', 'EducationLevel'), ('EXT', 'Extent'), ('FMT', 'Format'), ('HFMT', 'HasFormat'), ('HPT', 'HasPart'), ('HVS', 'HasVersion'), ('ID', 'Identifier'), ('IM', 'InstructionalMethod'), ('IFMT', 'IsFormatOf'), ('IPT', 'IsPartOf'), ('IREF', 'IsReferencedBy'), ('IREP', 'IsReplacedBy'), ('IREQ', 'IsRequiredBy'), ('IS', 'Issued'), ('IVSN', 'IsVersionOf'), ('LG', 'Language'), ('LI', 'License'), ('ME', 'Mediator'), ('MED', 'Medium'), ('MOD', 'Modified'), ('PRV', 'Provenance'), ('PBL', 'Publisher'), ('REF', 'References'), ('REL', 'Relation'), ('REP', 'Replaces'), ('REQ', 'Requires'), ('RT', 'Rights'), ('RH', 'RightsHolder'), ('SRC', 'Source'), ('SP', 'Spatial'), ('SUB', 'Subject'), ('TOC', 'TableOfContents'), ('TE', 'Temporal'), ('T', 'Title'), ('TYP', 'Type'), ('VA', 'Valid')], max_length=4)),
                ('qualifier', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['term'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiedDublinCoreElementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('term', models.CharField(choices=[('AB', 'Abstract'), ('AR', 'AccessRights'), ('AM', 'AccrualMethod'), ('AP', 'AccrualPeriodicity'), ('APL', 'AccrualPolicy'), ('ALT', 'Alternative'), ('AUD', 'Audience'), ('AVL', 'Available'), ('BIB', 'BibliographicCitation'), ('COT', 'ConformsTo'), ('CN', 'Contributor'), ('CVR', 'Coverage'), ('CRD', 'Created'), ('CR', 'Creator'), ('DT', 'Date'), ('DTA', 'DateAccepted'), ('DTC', 'DateCopyrighted'), ('DTS', 'DateSubmitted'), ('DSC', 'Description'), ('EL', 'EducationLevel'), ('EXT', 'Extent'), ('FMT', 'Format'), ('HFMT', 'HasFormat'), ('HPT', 'HasPart'), ('HVS', 'HasVersion'), ('ID', 'Identifier'), ('IM', 'InstructionalMethod'), ('IFMT', 'IsFormatOf'), ('IPT', 'IsPartOf'), ('IREF', 'IsReferencedBy'), ('IREP', 'IsReplacedBy'), ('IREQ', 'IsRequiredBy'), ('IS', 'Issued'), ('IVSN', 'IsVersionOf'), ('LG', 'Language'), ('LI', 'License'), ('ME', 'Mediator'), ('MED', 'Medium'), ('MOD', 'Modified'), ('PRV', 'Provenance'), ('PBL', 'Publisher'), ('REF', 'References'), ('REL', 'Relation'), ('REP', 'Replaces'), ('REQ', 'Requires'), ('RT', 'Rights'), ('RH', 'RightsHolder'), ('SRC', 'Source'), ('SP', 'Spatial'), ('SUB', 'Subject'), ('TOC', 'TableOfContents'), ('TE', 'Temporal'), ('T', 'Title'), ('TYP', 'Type'), ('VA', 'Valid')], max_length=4)),
                ('qualifier', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qdce_id_stored', models.PositiveIntegerField(help_text='Stores the id if the QulifiedDublinCoreElement the history points to is deleted.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('qdce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='dublincore.QualifiedDublinCoreElement')),
            ],
            options={
                'ordering': ['term'],
                'abstract': False,
            },
        ),
    ]
